Project/App/urls.py
from . import views
from django.urls import path

urlpatterns = [
  path('', views.PostList.as_view(), name="home"),
  path('<slug:slug>/', views.PostList.as_view(), name="post_detail"),
]

Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

Project/App/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

STATUS = ((0, "Draft"), (1, "Published"))

class Post(models.Model):
  title =  models.CharField(max_length=10000, unique=True)
  slug =   models.SlugField(max_length=10000, unique=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
  created_on = models.DateTimeField(auto_now_add=True)
  updated_on = models.DateTimeField(auto_now=True)
  content = models.TextField()
  status = models.IntegerField(choices=STATUS, default=0)

  class Meta:
    ordering = ['-created_on']

  def __str__(self):
    return self.title

Project/App/views.py
from django.shortcuts import render
from .models import Post
from django.views import generic 
# Create your views here.

class PostList(generic.ListView):
  queryset = Post.objects.filter(status=1).order_by('-created_on')
  template_name = 'index.html'


class DetailView(generic.DetailView):
  model = Post
  template_name = 'post_detail.html'
  

Project/App/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <title>AI Blog </title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <!-- Bootstrap cdn -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/journal/bootstrap.min.css"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/flatly/bootstrap.min.css">

  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/sketchy/bootstrap.min.css"> -->
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary" id="mainNav">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">🌍AI Blog Posts🧑‍💻</a>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="#">Reports</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="#">Policy</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}
  <!-- Content Goes here -->
  {% endblock content %}
  <!-- Footer -->
  <footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; 2022 AION</p>
  </footer>
</body>

</html>

Project/App/templates/index.html
{% extends "base.html" %}
{% block content %}
<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-md-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h3 class=" site-heading my-4 mt-3 text-black"> Welcome to My Blog ✍️ </h3>
          <p class="text-dark">Learn & Grow on AI everyday</p>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="row">
    <!-- Blog Entries Column -->
    <div class="col-md-8 mt-3 left">
      {% for post in post_list %}
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">{{ post.title }}</h2>
          <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
          <p class="card-text">{{post.content|slice:":200"}}</p>
          <a href="{% url 'post_detail' post.slug %}">Read more</a>
        </div>
      </div>
      {% endfor %}
    </div>
    {% block sidebar %} 
    {% include 'sidebar.html' %} 
    {% endblock sidebar %}
  </div>
</div>
{%endblock%}

Project/App/templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
        <p class="card-text">{{ object.body }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

Project/App/templates/sidebar.html
{% block sidebar %}

<style>
  .card {
    box-shadow: 0 16px 48px #6a6a6b;
  }
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
  <div class="card my-4">
    <h5 class="card-header">About</h5>
    <div class="card-body">
      <p class="card-text">This blog is about artificial Intelligence, machine learning, data science,AR & VR,blockchain and recent technology updates </p>
      <a href="https://github.com/Hem7513" class="btn btn-danger">Visit Git Hub!</a>
      <a href="https://twitter.com/HBG753" class="btn btn-secondary">Visit LinkedIN</a>
    </div>
  </div>
</div>

{% endblock sidebar %}